main: me.TurtlesAreHot.ElementChooser.Main
name: ElementChooser
version: 1.0.0
description: This plugin allows people to choose elements with the ProjectKorra plugin
author: TurtlesAreHot
api-version: 1.13
depend: [ProjectKorra]
commands:
  bluefire:
    description: Lets you switch between bluefire and no bluefire.
  choose:
    description: Lets you switch elements.
  darkspirit:
    description: Lets you add darkspirit.
  lightspirit:
    description: Lets you add lightspirit.
permissions:
  elementchooser.bluefire:
    description: Allows you to use the /bluefire command to switch between bluefire and no bluefire
    default: op
  elementchooser.choose.water:
    description: Allows you to choose water
    default: op
  elementchooser.choose.air:
    description: Allows you to choose air
    default: op
  elementchooser.choose.fire:
    description: Allows you to choose fire
    default: op
  elementchooser.choose.earth:
    description: Allows you to choose earth
    default: op
  elementchooser.choose.chi:
    description: Allows you to choose chi
    default: op
  elementchooser.choose.avatar:
    description: Allows you to choose avatar
    default: op
  elementchooser.choose.spirit:
    description: Allows you to choose spirits
    default: op
  elementchooser.choose.darkspirit:
    description: Allows you to choose darkspirit
    default: op
  elementchooser.choose.lightspirit:
    description: Allows you to choose lightspirit
    default: op
  elementchooser.lightspirit:
    description: Allows you to add lightspirit
    default: op
  elementchooser.darkspirit:
    description: Allows you to add darkspirit
    default: op